---
- name: Removing old docker versions
  apt:
    pkg:
      - docker 
      - docker-engine 
      - docker.io
      - containerd
      - runc
    state: absent
   
- name: Installing docker-ce dependencies
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
 
- name: Adding docker key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
     
- name: Constructing docker repository entry for apt configuration
  command: bash -c "echo \"deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable\" "
  register: docker_repo_line
 
- debug: 
    msg: "{{ docker_repo_line.stdout }}"
 
- name: Adding docker repository
  apt_repository:
    repo: "{{ docker_repo_line.stdout }}"
    state: present
      
- name: Installing docker-ce
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Installing Python packages for Docker
  apt:
    pkg:
      - python3-docker
    state: present
    update_cache: yes